const booksData = [
  { id: 1, title: "Clean Code", author: "Robert C. Martin", price: 1020 },
  { id: 2, title: "Machine Learning", author: "Tom M. Mitchell", price: 1450 },
  { id: 3, title: "C Programming", author: "Dennis Ritchie", price: 310 },
  { id: 4, title: "Operating System", author: "Abraham Silberschatz", price: 870 },
  { id: 5, title: "Angular", author: "Brad Green", price: 540 },
  { id: 6, title: "Artificial Neural Networks", author: "Simon Haykin", price: 1120 },
  { id: 7, title: "React JS", author: "Robin Wieruch", price: 670 },
  { id: 8, title: "Computer Networks", author: "Andrew S. Tanenbaum", price: 400 },
  { id: 9, title: "Data Mining", author: "Jiawei Han", price: 980 },
  { id: 10, title: "Docker", author: "Nigel Poulton", price: 850 },
  { id: 11, title: "Java", author: "Herbert Schildt", price: 720 },
  { id: 12, title: "Software Engineering", author: "Ian Sommerville", price: 940 },
  { id: 13, title: "DBMS", author: "Raghu Ramakrishnan", price: 600 },
  { id: 14, title: "Big Data Analytics", author: "Vijay Mayer-Schönberger", price: 1350 },
  { id: 15, title: "Node JS", author: "Mario Casciaro", price: 680 },
  { id: 16, title: "iOS Programming", author: "Paul Hegarty", price: 1190 },
  { id: 17, title: "Database Design", author: "Carlos Coronel", price: 940 },
  { id: 18, title: "Python", author: "Mark Lutz", price: 800 },
  { id: 19, title: "Mobile App Development", author: "Mark Murphy", price: 900 },
  { id: 20, title: "Web Development", author: "Jon Duckett", price: 520 },
  { id: 21, title: "Deep Learning", author: "Ian Goodfellow", price: 1490 },
  { id: 22, title: "Data Structures", author: "Seymour Lipschutz", price: 1030 },
  { id: 23, title: "Algorithms", author: "Robert Sedgewick", price: 880 },
  { id: 24, title: "Linear Algebra", author: "Gilbert Strang", price: 640 },
  { id: 25, title: "Computer Graphics", author: "Donald Hearn", price: 390 },
  { id: 26, title: "Probability & Statistics", author: "Sheldon Ross", price: 710 },
  { id: 27, title: "Software Architecture", author: "Len Bass", price: 1100 },
  { id: 28, title: "Compiler Design", author: "Alfred V. Aho", price: 940 },
  { id: 29, title: "GraphQL", author: "Lee Byron", price: 730 },
  { id: 30, title: "Design Patterns", author: "Erich Gamma", price: 1200 },
  { id: 31, title: "Angular", author: "Brad Green", price: 540 },
  { id: 32, title: "Cloud Computing", author: "Rajkumar Buyya", price: 1490 },
  { id: 33, title: "Cyber Security", author: "William Stallings", price: 1250 },
  { id: 34, title: "Object Oriented Analysis", author: "Grady Booch", price: 890 },
  { id: 35, title: "JavaScript Essentials", author: "Douglas Crockford", price: 610 },
  { id: 36, title: "Scrum Guide", author: "Ken Schwaber", price: 400 },
  { id: 37, title: "Refactoring", author: "Martin Fowler", price: 1030 },
  { id: 38, title: "Agile Methodology", author: "Mike Cohn", price: 510 },
  { id: 39, title: "Kubernetes", author: "Kelsey Hightower", price: 1340 },
  { id: 40, title: "HTML & CSS", author: "Elizabeth Robson", price: 350 },
  { id: 41, title: "TypeScript", author: "Anders Hejlsberg", price: 670 },
  { id: 42, title: "Android Programming", author: "Bill Phillips", price: 1110 },
  { id: 43, title: "REST API Design", author: "Leonard Richardson", price: 600 },
  { id: 44, title: "Operating Systems Concepts", author: "Silberschatz Galvin", price: 910 },
  { id: 45, title: "Digital Logic Design", author: "M. Morris Mano", price: 430 },
  { id: 46, title: "iOS Programming", author: "Paul Hegarty", price: 1190 },
  { id: 47, title: "Vue JS", author: "Evan You", price: 690 },
  { id: 48, title: "Machine Learning", author: "Tom M. Mitchell", price: 1450 },
  { id: 49, title: "Software Testing", author: "Ron Patton", price: 500 },
  { id: 50, title: "Database Design", author: "Carlos Coronel", price: 940 }
];

export default booksData;
